# Generated by Django 2.2.12 on 2020-04-21 03:09

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('kindoffood', models.CharField(help_text='What kind of food the ducks are fed?', max_length=200, verbose_name='Kind')),
                ('food', models.CharField(help_text='What food the ducks are fed?', max_length=200, verbose_name='Food')),
                ('how_much_food', models.PositiveIntegerField(help_text='KG, grams or units', verbose_name='How much food?')),
                ('measure', models.CharField(choices=[('KG', 'KG'), ('Gram', 'Gram'), ('Unit', 'Unit')], default='KG', help_text='What is the usual measure of the food the ducks are fed?', max_length=4, verbose_name='Measure')),
                ('how_many_ducks', models.PositiveIntegerField(help_text='How many ducks are fed?', verbose_name='Number of ducks')),
                ('fed_time', models.TimeField(help_text='What time the ducks are fed?', verbose_name='Time')),
                ('fed_everyday', models.BooleanField(blank=True, help_text='Do you feed the ducks everyday?', verbose_name='Feed everyday?')),
                ('address', django_google_maps.fields.AddressField(blank=True, help_text='What is the address where the ducks are fed?', max_length=200)),
                ('geolocation', django_google_maps.fields.GeoLocationField(blank=True, help_text='What are the coordinates where the ducks are fed?', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data created in')),
            ],
        ),
    ]
