# Generated by Django 2.2.12 on 2020-04-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20200418_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='fed_time',
            field=models.DateTimeField(verbose_name='What time the ducks are fed?'),
        ),
    ]
