# Generated by Django 2.2.12 on 2020-04-18 03:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20200418_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='kindoffood',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, verbose_name='What kind of food the ducks are fed?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='food',
            field=models.CharField(max_length=300, verbose_name='What food the ducks are fed?'),
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='KindOfFood',
        ),
    ]
