# Generated by Django 2.2.12 on 2020-04-18 05:44

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20200418_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, verbose_name='What is the address where the ducks are fed?'),
        ),
        migrations.AddField(
            model_name='lead',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, verbose_name='What are the coordinates where the ducks are fed?'),
        ),
    ]
