# Generated by Django 2.2.12 on 2020-04-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20200418_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='measure',
            field=models.CharField(choices=[('KG', 'KG'), ('Gram', 'Gram'), ('Unit', 'Unit')], default='KG', max_length=4, verbose_name='What is the usual measure of the food the ducks are fed?'),
        ),
    ]
