# Generated by Django 2.2.12 on 2020-04-19 01:30

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_auto_20200419_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, verbose_name='What is the address where the ducks are fed?'),
        ),
    ]
