# Generated by Django 2.2.12 on 2020-04-19 17:31

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_auto_20200419_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, help_text='What is the address where the ducks are fed?', max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='fed_everyday',
            field=models.BooleanField(blank=True, help_text='Do you feed the ducks everyday?', verbose_name='Feed everyday?'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='fed_time',
            field=models.DateTimeField(help_text='What time the ducks are fed?', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='food',
            field=models.CharField(help_text='What food the ducks are fed?', max_length=300, verbose_name='Food'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, help_text='What are the coordinates where the ducks are fed?', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='how_many_ducks',
            field=models.PositiveIntegerField(help_text='How many ducks are fed?', verbose_name='Number of ducks'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='how_much_food',
            field=models.PositiveIntegerField(help_text='KG, grams or units', verbose_name='How much food?'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='kindoffood',
            field=models.CharField(help_text='What kind of food the ducks are fed?', max_length=300, verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='measure',
            field=models.CharField(choices=[('KG', 'KG'), ('Gram', 'Gram'), ('Unit', 'Unit')], default='KG', help_text='What is the usual measure of the food the ducks are fed?', max_length=4, verbose_name='Measure'),
        ),
    ]
